version: '2'
services:
  mysql-awsdemo:
    image: mysql:5.7
    container_name: mysql-awsdemo
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=awsdemo
      - MYSQL_DATABASE=awsdemo
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"


  spring-awsdemo:
    image: prasadadireddi/awsdemo-spinnaker-jenkins
    container_name: spring-awsdemo
    mem_limit: 512M
    depends_on:
      - mysql-awsdemo
    ports:
     - 8080:8080
    environment:
     - SPRING_PROFILES_ACTIVE=mysql,prod
